"""One-line definitions for every genre style in the catalogue.

Definitions are concise and factual, drawn from standard music reference usage
(All Music Guide, Grove, Discogs editorial descriptions). Keyed by style name.
"""

from __future__ import annotations

DEFINITIONS: dict[str, str] = {
    # ── Jazz / Blues / Soul / Funk ──────────────────────────────────────────
    "Jazz": "Improvisation-driven music born in early-1900s New Orleans, blending blues, ragtime and brass-band traditions.",
    "Swing": "Big-band dance jazz of the 1930s-40s built on a propulsive, danceable rhythmic 'swing' feel.",
    "Bebop": "Fast, harmonically complex jazz pioneered in the 1940s by Charlie Parker and Dizzy Gillespie for listening over dancing.",
    "Hard Bop": "An earthier 1950s bebop offshoot pulling in blues, gospel and R&B influences.",
    "Modal Jazz": "Jazz organised around scales (modes) rather than chord changes, exemplified by Miles Davis's 'Kind of Blue'.",
    "Free Jazz": "Avant-garde jazz that abandons fixed chords, tempo and structure in favour of collective improvisation.",
    "Jazz Fusion": "The late-1960s merger of jazz improvisation with rock rhythms and electric instruments.",
    "Smooth Jazz": "Polished, radio-friendly jazz-pop emphasising melody and groove over improvisation.",
    "Contemporary Jazz": "An umbrella for modern jazz blending traditional forms with pop, funk and world influences.",
    "Acid Jazz": "A late-1980s club hybrid of jazz, funk, soul and hip-hop grooves, centred on London.",
    "Nu Jazz": "Electronic-leaning jazz fusing live improvisation with programmed beats and production.",
    "Blues": "Foundational African-American genre built on twelve-bar forms, blue notes and call-and-response.",
    "Delta Blues": "The raw, early acoustic blues of the Mississippi Delta, often solo guitar and slide.",
    "Chicago Blues": "Electrified, band-driven blues developed by Southern migrants in post-war Chicago.",
    "Electric Blues": "Blues amplified with electric guitar and a full rhythm section.",
    "Blues Rock": "A heavier fusion of electric blues and rock, pioneered by acts like Cream and Led Zeppelin.",
    "Soul": "Emotive 1960s African-American music fusing gospel fervour with R&B and pop.",
    "Motown": "The polished, pop-crossover soul sound of Detroit's Motown Records in the 1960s.",
    "Northern Soul": "A British scene celebrating obscure, up-tempo 1960s American soul records for all-night dancing.",
    "Southern Soul": "Grittier, gospel-rooted soul from studios in Memphis and Muscle Shoals.",
    "Funk": "Rhythm-first music led by James Brown, prioritising syncopated bass and drums 'on the one'.",
    "P-Funk": "The theatrical, psychedelic funk universe of George Clinton's Parliament-Funkadelic.",
    "Jazz-Funk": "Funk grooves crossed with jazz harmony and improvisation.",
    "New Jack Swing": "Late-1980s fusion of hip-hop beats with R&B singing, defined by producer Teddy Riley.",
    "Neo Soul": "1990s-2000s soul revival blending classic warmth with hip-hop and jazz, e.g. D'Angelo and Erykah Badu.",
    "R&B": "Rhythm and blues; the broad African-American popular tradition from which rock and soul descend.",
    "Contemporary R&B": "Modern, production-heavy R&B blending soul vocals with hip-hop, pop and electronic textures.",
    "Quiet Storm": "Smooth, late-night romantic soul named after a Smokey Robinson album and radio format.",
    "Gospel": "Sacred African-American vocal music and the wellspring of soul and much popular singing.",
    # ── Folk / World / Reggae ────────────────────────────────────────────────
    "Country": "American roots music descended from folk and Western traditions, built on storytelling.",
    "Bluegrass": "Fast, acoustic string-band country pioneered by Bill Monroe, featuring banjo and tight harmonies.",
    "Country Rock": "The late-1960s blend of country instrumentation with rock attitude.",
    "Outlaw Country": "A 1970s rebellion against Nashville polish, led by Willie Nelson and Waylon Jennings.",
    "Americana": "A modern roots umbrella spanning country, folk, blues and rock songwriting.",
    "Alternative Country": "Indie-minded country mixing traditional forms with punk and rock sensibilities.",
    "Country Pop": "Country songwriting smoothed for mainstream pop radio.",
    "Folk": "Acoustic, song-centred music rooted in traditional and topical storytelling.",
    "Contemporary Folk": "Modern singer-driven folk in the lineage of the 1960s revival.",
    "Folk Pop": "Folk melodies and acoustic textures arranged for pop accessibility.",
    "Indie Folk": "2000s folk filtered through indie-rock production and lo-fi intimacy.",
    "Psychedelic Folk": "Folk laced with the surreal, exploratory spirit of 1960s psychedelia.",
    "Neo-Folk": "Post-industrial acoustic music with darker, often esoteric themes.",
    "Singer-Songwriter": "Intimate, personal songcraft where the writer is also the performer.",
    "World Music": "A Western marketing umbrella for non-Western and traditional musics worldwide.",
    "Afrobeat": "Fela Kuti's politically charged fusion of Nigerian highlife, funk and jazz.",
    "Afrobeats": "The contemporary West-African pop wave blending Afrobeat roots with hip-hop, dancehall and R&B.",
    "Reggae": "Jamaica's signature genre, defined by the off-beat 'skank' guitar and deep bass.",
    "Roots Reggae": "Spiritual, Rastafarian-themed reggae of the 1970s, exemplified by Bob Marley.",
    "Ska": "Up-tempo precursor to reggae combining Caribbean mento with American R&B.",
    "Rocksteady": "The slower, soulful bridge between ska and reggae in mid-1960s Jamaica.",
    "Dub": "Studio-built reggae remixes stripped to bass and drums, drenched in echo and reverb.",
    "Dancehall": "Sparse, digital, DJ-toasting reggae that emerged in 1980s Jamaican sound systems.",
    "Lovers Rock": "Smooth, romantic British reggae focused on soulful singing.",
    "Reggaeton": "Latin urban music fusing dancehall's riddims with hip-hop, born in Puerto Rico.",
    "Cumbia": "A Colombian folk-dance rhythm that became one of Latin America's most widespread styles.",
    "Bossa Nova": "Brazil's gentle 1950s fusion of samba rhythm with cool-jazz harmony.",
    "Samba": "Brazil's national rhythm, rooted in Afro-Brazilian percussion and Carnival.",
    # ── Rock ─────────────────────────────────────────────────────────────────
    "Rock & Roll": "The mid-1950s explosion of blues, country and R&B that launched modern popular music.",
    "Rockabilly": "Early rock & roll's twangy fusion of hillbilly country and R&B.",
    "Surf": "Reverb-drenched instrumental rock evoking 1960s California beach culture.",
    "Garage Rock": "Raw, amateurish 1960s rock that prefigured punk.",
    "Psychedelic Rock": "1960s rock evoking the hallucinogenic experience with effects and extended jams.",
    "Acid Rock": "Heavier, louder psychedelic rock leaning toward hard rock.",
    "Folk Rock": "Folk songcraft electrified with rock instrumentation, e.g. The Byrds and Dylan.",
    "Classic Rock": "The canonical guitar-rock of the late-1960s through 1980s, now a radio format.",
    "Prog Rock": "Ambitious, conceptual rock with classical structures and virtuosic playing.",
    "Krautrock": "Experimental, hypnotic German rock of the early 1970s that shaped electronic music.",
    "Glam Rock": "Flamboyant, theatrical 1970s rock built on image and glam, e.g. Bowie and T. Rex.",
    "Soft Rock": "Mellow, melodic rock smoothed for adult pop radio.",
    "Southern Rock": "Blues- and country-tinged hard rock from the American South.",
    "Art Rock": "Experimental rock drawing on avant-garde and high-art ambitions.",
    "Hard Rock": "Loud, riff-driven rock built on distorted guitars and powerful vocals.",
    "Heavy Metal": "Darker, heavier rock defined by power, volume and virtuosic guitar.",
    "Speed Metal": "Fast, aggressive metal that bridged the NWOBHM and thrash.",
    "Thrash Metal": "Fast, tight, aggressive metal led by Metallica, Slayer and Megadeth.",
    "Death Metal": "Extreme metal with growled vocals, blast beats and morbid themes.",
    "Black Metal": "Raw, atmospheric extreme metal with shrieked vocals and lo-fi production.",
    "Doom Metal": "Slow, heavy, dread-laden metal descended from Black Sabbath.",
    "Stoner Rock": "Fuzzy, groove-heavy hard rock blending doom and psychedelia.",
    "Sludge Metal": "A thick, abrasive fusion of doom metal and hardcore punk.",
    "Gothic Metal": "Atmospheric metal blending doom heaviness with gothic romance and melody.",
    "Power Metal": "Fast, melodic, anthemic metal with soaring vocals and fantasy themes.",
    "Progressive Metal": "Technically complex metal with shifting time signatures and long compositions.",
    "Nu Metal": "Late-1990s metal fused with hip-hop, groove and angst, e.g. Korn and Limp Bizkit.",
    "Glam Metal": "Image-driven 1980s 'hair metal' built on hard-rock hooks and excess.",
    "Alternative Metal": "Metal crossed with alternative-rock experimentation and unconventional structures.",
    "Punk Rock": "Fast, stripped-down, anti-establishment rock that erupted in the mid-1970s.",
    "Hardcore Punk": "Faster, harder, more aggressive punk from the early-1980s US scene.",
    "Pop Punk": "Catchy, melodic punk with pop hooks, popularised by Green Day and blink-182.",
    "Post-Punk": "Arty, experimental music made in punk's wake, e.g. Joy Division and Wire.",
    "New Wave": "Punk-adjacent pop embracing synths, hooks and quirk, e.g. Talking Heads.",
    "Alternative Rock": "An umbrella for guitar rock outside the mainstream that broke through in the 1990s.",
    "Grunge": "Sludgy, angst-ridden Seattle rock fusing punk and metal, defined by Nirvana.",
    "Post-Grunge": "Radio-polished rock that followed grunge into the mainstream.",
    "Indie Rock": "Guitar rock made and released outside the major-label system, valuing authenticity.",
    "Post-Rock": "Instrumental rock using guitars for texture and dynamics rather than riffs.",
    "Math Rock": "Angular, rhythmically complex rock built on odd time signatures.",
    "Emo": "Confessional, emotionally raw offshoot of hardcore punk.",
    "Screamo": "An intense, screamed, chaotic strain of emo and hardcore.",
    "Noise Rock": "Dissonant, abrasive rock that foregrounds feedback and distortion.",
    "Shoegaze": "Dreamy, guitar-effects-drenched rock where vocals blur into a wall of sound.",
    "Dream Pop": "Lush, ethereal, atmospheric pop-rock with reverb-soaked textures.",
    "Britpop": "1990s British guitar pop celebrating UK identity, led by Oasis and Blur.",
    "Indie Pop": "Melodic, jangly, DIY pop in the indie tradition.",
    "Jangle Pop": "Bright, ringing guitar pop built on chiming twelve-string melodies.",
    "Power Pop": "Hook-laden rock blending Beatles melody with punchy energy.",
    "Bedroom Pop": "Intimate, lo-fi pop self-produced at home, a 2010s internet phenomenon.",
    "Metalcore": "A fusion of metal heaviness with hardcore punk's breakdowns and shouts.",
    "Deathcore": "An extreme blend of death metal and metalcore breakdowns.",
    "Mathcore": "Dissonant, technically chaotic fusion of metalcore and math rock.",
    # ── Pop ──────────────────────────────────────────────────────────────────
    "Pop": "Mainstream popular music engineered for broad, immediate appeal.",
    "Bubblegum": "Bright, simple, hook-driven pop aimed at a teen audience.",
    "Disco": "Four-on-the-floor dance music that ruled 1970s nightclubs.",
    "Dance-pop": "Up-tempo pop built for the dancefloor with strong beats and hooks.",
    "Synthpop": "Pop built primarily on synthesizers, defining the early-1980s sound.",
    "Electropop": "Synth-forward pop with a harder, more electronic edge.",
    "Teen Pop": "Polished pop marketed to teenagers, peaking with late-1990s boy bands and divas.",
    "Adult Contemporary": "Soft, melodic pop aimed at an older mainstream radio audience.",
    "Europop": "Catchy, accessible continental European pop.",
    "Eurodance": "Up-tempo 1990s European dance-pop with rap verses and sung choruses.",
    "Hi-NRG": "Fast, energetic electronic dance music rooted in disco's club scene.",
    "Italo-Disco": "Synth-heavy Italian disco that shaped house and Eurodance.",
    "Nu-Disco": "A 2000s revival of disco and boogie filtered through modern dance production.",
    "K-Pop": "South Korean pop combining slick production, choreography and idol culture.",
    "J-Pop": "Japanese mainstream pop spanning rock, dance and idol traditions.",
    "City Pop": "Glossy, urban Japanese pop of the late-1970s and 80s, recently rediscovered online.",
    "Hyperpop": "Maximalist, hyper-processed pop pushing autotune and distortion to extremes.",
    "PC Music": "A label and aesthetic of glossy, hyper-synthetic, ironic pop.",
    "Bubblegum Bass": "Sugary, abrasive electronic pop foundational to hyperpop.",
    "Tropical House": "Mellow, melodic house with a laid-back, sun-soaked feel.",
    "Slap House": "Bass-heavy house built on a distinctive 'slap' bassline, big on streaming in the late 2010s.",
    # ── Electronic ───────────────────────────────────────────────────────────
    "Electronic": "Music created primarily with electronic instruments and production technology.",
    "Ambient": "Atmospheric, often beatless music designed to colour a space, coined by Brian Eno.",
    "Dark Ambient": "Brooding, dissonant ambient music evoking dread and isolation.",
    "Drone": "Minimalist music built on sustained, slowly evolving tones.",
    "Industrial": "Harsh, mechanical, confrontational electronic music born of the late 1970s avant-garde.",
    "EBM": "Electronic Body Music; danceable, militant industrial with chanted vocals.",
    "Dark Electro": "Aggressive, distorted, darker offshoot of EBM and industrial.",
    "Aggrotech": "Harsh, abrasive dark-electro with distorted, screamed vocals.",
    "Futurepop": "Melodic, accessible electronic music descended from EBM and trance.",
    "New Beat": "Slow, hypnotic late-1980s Belgian electronic dance music.",
    "House": "Four-on-the-floor dance music born in 1980s Chicago clubs, the foundation of modern dance music.",
    "Deep House": "Soulful, jazzy, atmospheric house with lush chords.",
    "Acid House": "House defined by the squelching Roland TB-303 bassline, igniting the late-80s rave era.",
    "Chicago House": "The original house sound from its 1980s Chicago birthplace.",
    "Garage House": "Soulful, vocal-led house from New York's Paradise Garage scene.",
    "Tech House": "A blend of techno's mechanical drive with house's groove.",
    "Progressive House": "Hypnotic, gradually building house with long, layered arrangements.",
    "Tribal House": "Percussion-heavy house built on tribal drum patterns.",
    "Funky House": "House built on filtered disco and funk samples.",
    "Afro House": "House infused with African percussion, melody and vocal traditions.",
    "Organic House": "Warm, downtempo house woven with acoustic and world textures.",
    "Detroit Techno": "The original techno, born from Detroit's fusion of funk, electro and futurism.",
    "Techno": "Repetitive, machine-driven electronic dance music built around the drum machine.",
    "Minimal Techno": "Stripped-back techno built on subtle, hypnotic repetition.",
    "Dub Techno": "Techno fused with dub's deep echo and cavernous space.",
    "Industrial Techno": "Harsh, distorted, abrasive techno drawing on industrial textures.",
    "Melodic Techno": "Emotive, atmospheric techno foregrounding melody and mood.",
    "Trance": "Hypnotic, melodic electronic dance music built on euphoric builds and breakdowns.",
    "Progressive Trance": "Smoother, more layered and gradually evolving trance.",
    "Psytrance": "Fast, psychedelic trance built on swirling, hypnotic layers.",
    "Goa Trance": "The original psychedelic trance born on the beaches of Goa, India.",
    "Full-On": "A high-energy, melodic strain of psytrance.",
    "Darkpsy": "Fast, dark, dense and dissonant psytrance.",
    "Electro": "Robotic, electro-funk dance music built on the Roland TR-808, foundational to hip-hop.",
    "Breakbeat": "Dance music built on syncopated, broken drum patterns rather than a steady four-four.",
    "Big Beat": "Loud, rock-influenced breakbeat made for festivals, e.g. The Prodigy and Fatboy Slim.",
    "Rave": "Hardcore breakbeat-and-piano dance music of the early-1990s UK rave scene.",
    "Hardcore": "Extremely fast, intense electronic dance music descended from rave.",
    "Gabber": "Harsh, very fast Dutch hardcore techno with distorted kicks.",
    "Happy Hardcore": "Fast, euphoric, melodic rave music with sped-up vocals.",
    "Jungle": "Fast, breakbeat-driven UK dance music with deep reggae basslines.",
    "Drum n Bass": "Fast breakbeats over heavy sub-bass, evolved from jungle.",
    "Liquid Funk": "Smooth, melodic, soulful drum and bass.",
    "Neurofunk": "Dark, technical, bass-heavy drum and bass.",
    "UK Garage": "Soulful, swung British dance music descended from house and 2-step.",
    "2-Step": "A skippy, syncopated strain of UK garage with irregular kick patterns.",
    "Speed Garage": "Fast, bass-heavy UK garage with rave and jungle influences.",
    "Trip Hop": "Downtempo, atmospheric beats fusing hip-hop, soul and electronic, e.g. Massive Attack.",
    "IDM": "Intelligent Dance Music; cerebral, experimental electronic music for listening.",
    "Breakcore": "Frenetic, chaotic music built on chopped, overloaded breakbeats.",
    "Noise": "Abrasive sound art that foregrounds dissonance and texture over melody.",
    "Glitch": "Music built from digital errors, clicks, skips and artifacts.",
    "Microhouse": "Minimal, clicky house built from tiny, glitchy sound fragments.",
    "Minimal": "Stripped-back electronic dance music built on subtle, repetitive elements.",
    "Dubstep": "UK bass music defined by sparse, syncopated rhythms and wobbling sub-bass.",
    "Post-Dubstep": "Atmospheric, genre-blurring music that moved beyond dubstep's template.",
    "Brostep": "Aggressive, mid-range-heavy American dubstep, popularised by Skrillex.",
    "Grime": "Fast, abrasive UK electronic rap that emerged from East London in the early 2000s.",
    "UK Bass": "A broad umbrella for bass-led UK club music after dubstep and grime.",
    "Future Garage": "Atmospheric, emotive evolution of UK garage and 2-step.",
    "Bass Music": "An umbrella term for low-end-focused electronic club styles.",
    "EDM": "Electronic Dance Music; the festival-scaled, mainstream peak of dance music in the 2010s.",
    "Electro House": "Aggressive, heavy house with distorted basslines, big in the late 2000s.",
    "Chillwave": "Hazy, nostalgic, lo-fi electronic pop of the late-2000s blogosphere.",
    "Vaporwave": "Ironic, nostalgic music built from slowed, chopped 1980s corporate and lounge samples.",
    "Synthwave": "Retro-futurist electronic music evoking 1980s film and game soundtracks.",
    "Darksynth": "Darker, heavier, horror-tinged synthwave.",
    "Outrun": "Neon-soaked synthwave evoking 1980s arcade and driving aesthetics.",
    "Lo-Fi Hip Hop": "Mellow, imperfect, beat-driven instrumental hip-hop made for studying and relaxing.",
    "Footwork": "Fast, skittering Chicago dance music built for competitive footwork battles.",
    "Juke": "The booty-bass Chicago club precursor to footwork.",
    "Future Bass": "Melodic electronic music with lush, pitch-bent synth chords.",
    "Deconstructed Club": "Experimental, fragmented club music that dismantles dancefloor conventions.",
    # ── Hip-Hop ────────────────────────────────────────────────────────────────
    "Hip Hop": "Culture and music built on rapping, DJing, sampling and beats, born in 1970s New York.",
    "Old School Hip Hop": "The foundational hip-hop of the late-1970s and early-80s, party-focused and breakbeat-driven.",
    "East Coast Hip Hop": "New York-rooted hip-hop known for dense lyricism and sample-based beats.",
    "West Coast Hip Hop": "California hip-hop defined by laid-back funk samples and G-funk.",
    "Gangsta Rap": "Hardcore rap depicting street and gang life, controversial and commercially dominant.",
    "G-Funk": "Smooth, funk-sampling West Coast rap pioneered by Dr. Dre.",
    "Boom Bap": "Classic East Coast hip-hop built on hard, swinging drum breaks.",
    "Abstract Hip Hop": "Experimental, abstract, often instrumental hip-hop.",
    "Alternative Hip Hop": "Hip-hop that defies mainstream conventions, drawing on jazz, rock and funk.",
    "Conscious Hip Hop": "Socially and politically aware rap focused on message over materialism.",
    "Instrumental Hip Hop": "Beat-driven hip-hop with no vocals, foregrounding the producer.",
    "Jazz Rap": "Hip-hop built on jazz samples and live instrumentation.",
    "Dirty South": "Southern US hip-hop known for heavy bass and club-ready beats.",
    "Crunk": "Loud, chant-driven, party-focused Southern rap.",
    "Snap": "Minimalist Southern rap built on finger-snaps and sparse beats.",
    "Chopped and Screwed": "A Houston remix technique slowing and chopping tracks into a woozy haze.",
    "UK Hip Hop": "British rap with its own slang, accents and production traditions.",
    "French Hip Hop": "France's vibrant rap scene, one of the largest outside the US.",
    "Trap": "Hi-hat-rolling, 808-heavy Southern rap that became the dominant pop sound of the 2010s.",
    "Drill": "Dark, menacing, sliding-808 rap born in Chicago and reshaped in UK and Brooklyn scenes.",
    "Cloud Rap": "Hazy, ethereal, atmospheric rap built on dreamy, reverb-heavy beats.",
    "Mumble Rap": "Melodic, slurred-delivery rap prioritising mood and flow over enunciation.",
    "Emo Rap": "Melancholy rap fusing trap beats with emo and rock sensibilities.",
    "Phonk": "Lo-fi rap built on Memphis-rap samples and cowbell, huge on 2020s social media.",
    "Trap Soul": "Moody fusion of trap production with smooth R&B singing, defined by Bryson Tiller.",
    # ── catch-alls / families ──────────────────────────────────────────────────
    "Music": "Recorded sound organised into a documented release.",
}
